name: CI solamente
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 #descarga el repositorio en el ejecutor
 
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
            java-version: '8'
            distribution: 'adopt'
            server-id: github
            settings-path: ${{ github.workspace }} # location for the settings.xml file
           
      #### BUILDS ######
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 2.1
                  
      - name: build del Front
        working-directory: src/Clients
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
           name: Clients
           path: src/Clients/build/libs
     
      - name: build del Back
        working-directory: src/Backend/OrderService
        run: ./gradlew build test

      # --- A PARTIR DE AQUÍ: DOCKERIZAR Y PUBLICAR ---
      - name: dockerizar el front y el backend
        run: |
          cp src/Clients/build/libs/*.war deploy/docker/Clients/drop/
          docker build -t p2gps/web deploy/docker/Clients
          cp src/Backend/OrderService/build/libs/ordering* deploy/docker/Order/drop/
          docker build -t p2gps/order deploy/docker/Order

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Etiquetar y subir a DockerHub
        run: |
          docker tag p2gps/web ${{ secrets.DOCKERHUB_USERNAME }}/p2gps:web
          docker tag p2gps/order ${{ secrets.DOCKERHUB_USERNAME }}/p2gps:order
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/p2gps:web
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/p2gps:order
